services:
  - type: web
    name: agri-ecommerce-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-app-name.onrender.com/api # Replace with your actual backend Render URL
